name: xiongmao_reader
description: A new Flutter project.
version: 1.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flukit: ^1.0.2
  flutter_screenutil: ^0.7.0
  battery: ^0.3.0
  device_info: ^0.4.0
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6
  dio: ^2.1.13
  cached_network_image: ^2.0.0
  flutter_cache_manager: ^1.0.0
  flutter_easyrefresh: ^1.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - asset/
    - asset/icon/
    - asset/readers/
    - asset/books/
    - mock/