name: xiongmao_reader
description: i娱乐，熊猫互娱出品
version: 1.1.6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flukit: ^1.0.2
  flutter_screenutil: ^0.7.0
  screen: ^0.0.5
  battery: ^0.3.0
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6
  dio: ^2.1.13
  cached_network_image: ^2.0.0
  flutter_cache_manager: ^1.0.0
  flutter_easyrefresh: ^1.2.7
  flutter_html: ^0.11.1
  city_pickers: ^0.1.30
  amap_location: ^0.2.0
  permission_handler: ^3.2.0
  webview_plugin:
     path: webview_plugin/
  video_player: ^0.10.8+1
  #flutter_xupdate: ^0.0.2
  #极光推送
  jpush_flutter: ^0.5.3
  #获取app信息
  package_info: ^0.4.0+14
  #跳转第三方
  url_launcher: ^5.4.2
  flutter_swiper: ^1.1.6
  awsome_video_player: ^1.0.6

  path_provider: ^1.3.0
  install_plugin: ^2.0.1
  #chewie: ^0.9.10
 # event_bus: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - asset/
    - asset/me/
    - asset/icon/
    - asset/readers/
    - asset/books/
    - asset/recommends/
    - asset/recommends/weather/